import { keyboard, mouse, Button } from '@nut-tree-fork/nut-js'
import { nutKeyFor, keycodeForName } from './keymap'

// Fire as fast as the OS allows; we manage our own pacing in the engine.
keyboard.config.autoDelayMs = 0
mouse.config.autoDelayMs = 0

// ---------------------------------------------------------------------------
// Synthetic-input guard (per key).
//
// nut-js drives input through the OS, so uiohook sees our simulated presses as
// if they were physical. The hold-to-spam listeners must ignore *our own* keys
// — but only the specific keys we are actually synthesizing. A global guard
// (the previous approach) also swallowed the user's real release of the hold
// key whenever it landed during a spam burst, so the spammer never stopped.
//
// Tokens match the format the hold listeners use: `k:<keycode>` / `m:<button>`.
// ---------------------------------------------------------------------------
const COOLDOWN_MS = 20

const depth = new Map<string, number>()
const cooldownUntil = new Map<string, number>()
let globalCooldownUntil = 0 // brief catch-all while typeText() fires many keys

function begin(token: string | null): void {
  if (!token) return
  depth.set(token, (depth.get(token) ?? 0) + 1)
}

function end(token: string | null): void {
  if (!token) return
  depth.set(token, Math.max(0, (depth.get(token) ?? 0) - 1))
  cooldownUntil.set(token, Date.now() + COOLDOWN_MS)
}

/** True if `token`'s recent input was generated by us, not the user. */
export function isSyntheticToken(token: string): boolean {
  if (Date.now() < globalCooldownUntil) return true
  if ((depth.get(token) ?? 0) > 0) return true
  const until = cooldownUntil.get(token)
  return until !== undefined && Date.now() < until
}

function keyToken(name: string): string | null {
  const code = keycodeForName(name)
  return code === null ? null : `k:${code}`
}

/** Press and release a single logical key. */
export async function pressKey(name: string): Promise<void> {
  const token = keyToken(name)
  begin(token)
  try {
    const nutKey = nutKeyFor(name)
    if (nutKey !== null) {
      await keyboard.type(nutKey)
    } else {
      // Printable single characters (and anything not in the special table)
      // are typed literally.
      await keyboard.type(name)
    }
  } finally {
    end(token)
  }
}

/** Type a full string in one go. */
export async function typeText(text: string): Promise<void> {
  if (!text) return
  // Many distinct keys fire here; guard everything briefly rather than per-key.
  globalCooldownUntil = Date.now() + 60
  try {
    await keyboard.type(text)
  } finally {
    globalCooldownUntil = Date.now() + COOLDOWN_MS
  }
}

export async function clickMouse(button: 'left' | 'right'): Promise<void> {
  const token = `m:${button === 'left' ? 1 : 2}`
  begin(token)
  try {
    await mouse.click(button === 'left' ? Button.LEFT : Button.RIGHT)
  } finally {
    end(token)
  }
}
